name: Auto Merge

on:
  push:
    branches:
      - main

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Auto Merge
        run: |
          # Add any custom scripts or commands here to perform the merge
          git config user.name "KhulnaSoft-Lab"
          git config user.email "security@khulnasoft.com"
          git checkout main
          git merge ${{ github.event.before }}
          git push
